//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATHANG
    {
        public string MaKH { get; set; }
        public string MaHH { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string DienGiai { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
